{
 "title": "output2postgres",
 "description": "Demo dashboard for output2postgres.py",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Testsuite_var",
    "label": "Test Suite",
    "query": "select distinct testsuite from testrun_results"
   }
  ]
 },
 "panels": [
  {
   "title": "Total testruns",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM testrun_results WHERE testsuite IN ($Testsuite_var) and $__timeFilter(starttime)  "
    }
   ]
  },
  {
   "title": "Avg Succes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(passed) FROM testrun_results WHERE testsuite IN ($Testsuite_var) AND $__timeFilter(starttime) "
    },
    {
     "rawSql": "SELECT SUM(total) FROM testrun_results WHERE testsuite IN ($Testsuite_var) AND $__timeFilter(starttime) "
    },
    { "expression": "($A/$B)*100", "type": "math" }
   ]
  },
  {
   "title": "Avg Fail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(failed) FROM testrun_results WHERE testsuite IN  ($Testsuite_var) AND $__timeFilter(starttime) "
    },
    {
     "rawSql": "SELECT SUM(total) FROM testrun_results WHERE testsuite IN ($Testsuite_var) AND $__timeFilter(starttime) "
    },
    { "expression": "($A/$B)*100", "type": "math" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT testsuite,starttime, endtime, passed, failed, elapsedtime FROM testrun_results WHERE testsuite IN ($Testsuite_var ) AND $__timeFilter(starttime) LIMIT 50 "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select a.testsuite, b.testsuite as col2, c.testcase, (regexp_split_to_array (d.json ->0->>'message' , '\\n'))[1] as omschrijving from \"testrun_results\" A\r\ninner join \"suite_results\" B on A.id = B.testrunid\r\ninner join \"test_results\" C on B.id = C.testsuiteid\r\ninner join \"test_results_json\" D on C.id = D.testresultid\r\nwhere c.status = 'FAIL' AND a.testsuite IN  ($Testsuite_var) AND $__timeFilter(a.starttime) \r\n\r\norder by a.testsuite asc, c.starttime asc;"
    }
   ]
  }
 ]
}